### ISSUE TITLE
Preparation for Frenkel-Ladd Path

### ISSUE THREAD

**Issue by ibrsam** [freitas-rodrigo/FreeEnergyLAMMPS#2]

**Comment by haomaoshengaaa** [comment]
> Please, can you provide the scripts to calculate the equilibrium lattice parameter and the spring constant. The example commands provided in the paper are helpful, but it kind of confusing how to implement it. So, it would be great if you can provide an example or script to run these simulations.
> 
> Many thanks!

Hello,I have the same problem now when trying to calculate the lattice parameter and spring constant  of bcc iron at 100K. I am not sure if you have  solved this .Could you give me some help ? I would appreciate a lot .

**Comment by freitas-rodrigo** [comment]
Folks, the calculation of these parameters should be covered in any
textbook on MD simulations. Unfortunately I don't have time to provide
scripts for these tasks, but they are elementary enough that anyone with
expertise in MD simulations should be able to help you.

For the spring constants see for example eq 23 of the paper or eq. (10.2.4)
in Frenkel and Smit - "Understanding molecular simulation". LAMMPS already
has a command to compute the MSD for you.

**Comment by haomaoshengaaa** [comment]
Many thanks for your reply. I have soveld the problem and sorry for my silly question.------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月25日(星期三) 晚上10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [freitas-rodrigo/FreeEnergyLAMMPS] Preparation for Frenkel-Ladd Path (#2)
